[package]
name = "datafusion-postgres"
version = "0.4.0"
edition = "2021"
rust-version = "1.82.0"
description = "Exporting datafusion query engine with postgres wire protocol"
authors = ["Ning Sun <sunng@pm.me>"]
license = "Apache-2.0"
keywords = ["database", "postgresql"]
homepage = "https://github.com/sunng87/datafusion-postgres/"
repository = "https://github.com/sunng87/datafusion-postgres/"
documentation = "https://docs.rs/crate/datafusion-postgres/"
readme = "../README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
bytes = "1.10.1"
chrono = { version = "0.4", features = ["std"] }
datafusion = { workspace = true }
futures = "0.3"
log = "0.4"
pgwire = { workspace = true }
postgres-types = "0.2"
rust_decimal = { version = "1.37", features = ["db-postgres"] }
tokio = { version = "1.45", features = ["sync"] }
